### ISSUE TITLE
Missing metadata

### ISSUE THREAD

**Issue by komposer-aml** [elkrien/spotify-player#11]
Hello :)

I noticed that when I switch to a Catpuccin theme, the metadata showing whether shuffle, repeat, volume, etc below the song name goes away - even if app.toml specifies it should be there

Here's an example:
**Default Theme**
![image](https://github.com/user-attachments/assets/6ef5e763-eedd-4054-83b9-cafb35eddff6)

**catpuccin-macchiato**
![image](https://github.com/user-attachments/assets/4b1f9d41-ae23-47ad-805d-93e36e480c84)

It almost feels intentional, so I was unsure if I should even raise an issue, but I thought I'd bring it up and get clarification before taking the time to create a PR

**Comment by w-lfchen** [comment]
the metadata is not the only thing seemingly missing, see #12
if this was intentional, i don't think it's a good default to display less information, but i don't think it was
