### ISSUE TITLE
Selection_Background is Incorrectly Formatted

### ISSUE THREAD

**Issue by manolipt** [elkrien/spotify-player#2]
The config currently on master causes `spotify_player` to crash since "SelectionBackground" is not one of the color fields provided by the application. The fix is pretty straightforward: remove the `selection_background` and `selection_foreground` specifiers in the theme palette, and replace them with `bg = { Rgb { r = ..., g = ..., b = ... } }` where appropriate

I've made this fix on my local machine with the correct color codes and can push to a branch in a bit if I have permissions to do so

**Comment by elkrien** [comment]
Feel free to make a PR

**Comment by elkrien** [comment]
OK, I think I fixed the issue, please test if possible.

**Comment by manolipt** [comment]
Just tested, works great! Thanks :)
