### ISSUE TITLE
Error when setting theme

### ISSUE THREAD

**Issue by claykom** [elkrien/spotify-player#4]
What Happened: I had just install spotify-player via cargo with the default options. I tried to set the theme per instillation instructions and received the following error

OS: Ubuntu LTS 22.04.3

 Error: TOML parse error at line 26, column 20                                   
   |                                                                            
26 | selection = { bg = { Rgb = { r = 49, g = 50, b = 68 } }, modifiers = ["Bold
"] }                                                                            
   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                    
invalid type: map, expected a string  

To Reproduce: Install spotify-player via cargo with default options => Clone this repository => Move theme.toml to config location => Set app.toml theme value and reload spotify-player; you will receive this error.

To remove you must remove the theme.toml file and set the config in app.toml back to the default selection

**Comment by elkrien** [comment]
Fixed. Should be working now. Please test.

**Comment by claykom** [comment]
The bug has been fixed; thank you.
